general {
    lock_cmd = pidof hyprlock || hyprlock       # bloquea, salvo que hyprlock ya este abierto.
    before_sleep_cmd = loginctl lock-session    # bloquea la sesion antes de suspender.
    after_sleep_cmd = hyprctl dispatch dpms on  # enciende el monitor al despertar.
}

# sin actividad: atenua la pantalla.
listener {
    timeout = 150                                # 2.5min.
    on-timeout = brightnessctl -s set 15%        # baja el brillo.
    on-resume = brightnessctl -r                 # al mover el raton o pulsar una tecla, restaura el brillo.
}

# apaga la luz del teclado (si el equipo la tiene).
listener {
    timeout = 150                                          # 2.5min.
    on-timeout = ~/.config/hypr/scripts/kbd-backlight.sh off
    on-resume = ~/.config/hypr/scripts/kbd-backlight.sh on
}

# bloquea la pantalla.
listener {
    timeout = 300                                 # 5min
    on-timeout = loginctl lock-session
}

# apaga la pantalla.
listener {
    timeout = 330                                 # 5.5min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# suspende el equipo.
listener {
    timeout = 1800                                # 30min
    on-timeout = systemctl suspend
}

# Resumen: 2.5 min baja el brillo, 5 min bloquea, 5.5 min apaga la pantalla, 30 min suspende.
